InsuranceApp/ViewModels/RegisterForCustomersViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InsuranceApp.ViewModels
{
    public class RegisterForCustomersViewModel
    {
        public Guid Id { get; set; }
        [Required(ErrorMessage = "Please enter customer name.")]
        public string CustomerName { get; set; }
        [Required(ErrorMessage = "Please enter Your Information.")]
        public string FirstPart { get; set; }

        [Required(ErrorMessage = "Please enter Your Information.")]
        public string SecondPart { get; set; }
        [Required(ErrorMessage = "Please enter Your Number.")]
        [Display(Name = "NRC No : ")]
        public string NRCnumber { get; set; }
        [Required(ErrorMessage = "Please enter Your phone number.")]
        public string PhoneNo { get; set; }
        [Required(ErrorMessage = "Please enter Email.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please select city.")]
        public string CityName { get; set; }
        public Guid CityId { get; set; }
        [Required(ErrorMessage = "Please select Township.")]
        public string TownshipName { get; set; }
        public Guid TownshipId { get; set; }
        [Required(ErrorMessage = "Please enter your address.")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please enter date of birth.")]
        [Display(Name = "Date Of Birth : ")]
        public DateTime DOB { get; set; }
        [Required(ErrorMessage = "Please select gender.")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please select Photo.")]
        public string photo { get; set; }
        public List<RegisterForCustomersViewModel> RegCustomers = new List<RegisterForCustomersViewModel>();
        public List<CityViewModel> Cities = new List<CityViewModel>();
        public List<TownshipsViewModel> Townships = new List<TownshipsViewModel>();
        public List<SelectListItem> FirstParts = new List<SelectListItem>();
        public List<SelectListItem> SecondParts = new List<SelectListItem>();
    }
}

InsuranceApp/Controllers/RegisterForCustomersController.cs
using InsuranceApp.Models;
using InsuranceApp.Services;
using InsuranceApp.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InsuranceApp.Controllers
{
    [Authorize(Roles = "Admin,Staff")]
    public class RegisterForCustomersController : Controller
    {
        private readonly ApplicationDbContext _context = new ApplicationDbContext();
        private readonly RegisterForCustomersService _customerService = new RegisterForCustomersService();
        private readonly CityService _cityService = new CityService();
        private readonly TownshipService _townShipService = new TownshipService();
        // GET: RegisterForCustomers
        #region NRC
        List<SelectListItem> _firstParts = new List<SelectListItem>
            {
                new SelectListItem {Value="1",Text="1" },
                new SelectListItem {Value="2",Text="2" },
                new SelectListItem {Value="3",Text="3" },
                new SelectListItem {Value="4",Text="4" },
                new SelectListItem {Value="5",Text="5" },
                new SelectListItem {Value="6",Text="6" },
                new SelectListItem {Value="7",Text="7" },
                new SelectListItem {Value="8",Text="8" },
                new SelectListItem {Value="9",Text="9t" },
                new SelectListItem {Value="10",Text="10" },
                new SelectListItem {Value="11",Text="11" },
                new SelectListItem {Value="12",Text="12" }
            };
        List<SelectListItem> _secondParts = new List<SelectListItem>
            {

                new SelectListItem {Value="A La Na",Text="2" },
                new SelectListItem {Value="A SA NA",Text="3" },
                new SelectListItem {Value="BA HA NA",Text="4" },
                new SelectListItem {Value="DA TA HTA",Text="5" },
                new SelectListItem {Value="DA GA HSA",Text="6" },
                new SelectListItem {Value="DA GA NA",Text="7" },
                new SelectListItem {Value="DA GA RA",Text="8" },
                new SelectListItem {Value="DA HGA TA",Text="9t" },
                new SelectListItem {Value="DA LA NA",Text="10" },
                new SelectListItem {Value="DA PA NA",Text="11" },
                new SelectListItem {Value="HTA TA PA",Text="12" },
                 new SelectListItem {Value="KA KA KA",Text="2" },
                new SelectListItem {Value="KA KHA KA",Text="3" },
                new SelectListItem {Value="KA MA NA",Text="4" },
                new SelectListItem {Value="KA MA RA",Text="5" },
                new SelectListItem {Value="KA MA TA",Text="6" },
                new SelectListItem {Value="KA TA NA",Text="7" },
                new SelectListItem {Value="KA TA TA",Text="8" },
                new SelectListItem {Value="KHA RA NA",Text="9t" },
                new SelectListItem {Value="LA KA NA",Text="10" },
                new SelectListItem {Value="LA MA TA",Text="11" },
                new SelectListItem {Value="LA THA YA",Text="12" },
                new SelectListItem {Value="MA BHA NA",Text="2" },
                new SelectListItem {Value="MA GA DA",Text="3" },
                new SelectListItem {Value="MA GA TA",Text="4" },
                new SelectListItem {Value="MA RA KA",Text="5" },
                new SelectListItem {Value="PA BHA TA",Text="6" },
                new SelectListItem {Value="PA ZA TA",Text="7" },
                new SelectListItem {Value="RA KA NA",Text="8" },
                new SelectListItem {Value="RA KA THA",Text="9t" },
                new SelectListItem {Value="SA KHA NA",Text="10" },
                new SelectListItem {Value="TA KA NA",Text="11" },
                new SelectListItem {Value="TA TA HTA",Text="12" },
                new SelectListItem {Value="TA TA NA",Text="4" },
                new SelectListItem {Value="THA KA TA",Text="5" },
                new SelectListItem {Value="THA KHA NA",Text="6" },
                new SelectListItem {Value="THA LA NA",Text="7" },
                new SelectListItem {Value="U KA MA",Text="8" },
                new SelectListItem {Value="U Ka Ta",Text="U Ka Ta" },
            };
        #endregion
        public ActionResult Index()
        {
            List<RegisterForCustomersViewModel> model = _customerService.GetCustomers();
            return View(model);
        }
        public ActionResult CreateCustomers()
        {
            RegisterForCustomersViewModel model = new RegisterForCustomersViewModel();
            model.RegCustomers = _customerService.GetRegCustomersForDropdown();
            model.Cities = _cityService.GetCities();
           
            model.FirstParts = _firstParts;
            model.SecondParts = _secondParts;
            return View(model);
        }
        [HttpPost]
        public ActionResult CreateCustomers(RegisterForCustomersViewModel viewModel, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                string fileName = Path.GetFileName(file.FileName);
                string imgPath = Path.Combine(Server.MapPath("~/Images/"), fileName);
                file.SaveAs(imgPath);
            }
            string Img = "~/Images/" + file.FileName;
            string currentUserId = User.Identity.GetUserId();
            _customerService.CreateCustomers(viewModel,Img, currentUserId);
            return RedirectToAction("Index");
        }
        public ActionResult Edit(Guid id)
        {
            
            RegisterForCustomersViewModel model = _customerService.GetCustomerById(id);
            ViewBag.Address = model.Address;
                model.RegCustomers = _customerService.GetRegCustomersForDropdown();
                model.Cities = _cityService.GetCities();
                model.Townships = _townShipService.GetTownships();
                model.FirstParts = _firstParts;
                model.SecondParts = _secondParts;
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(RegisterForCustomersViewModel viewModel,HttpPostedFileBase file)
        {
            string currentUserId = User.Identity.GetUserId();
            
            if (file != null && file.ContentLength > 0)
            {
                string fileName = Path.GetFileName(file.FileName);
                string imgPath = Path.Combine(Server.MapPath("~/Images/"), fileName);
                file.SaveAs(imgPath);
            }
            string img = "~/Images/" + file.FileName;
            _customerService.Edit(viewModel,img, currentUserId);
            return RedirectToAction("Index");
        }
        public ActionResult Delete(Guid id)
        {
            _customerService.Delete(id);
            return RedirectToAction("Index");
        }
        public ActionResult DetailUser(Guid id)
        {

            RegisterForCustomersViewModel model = _customerService.GetCustomerById(id);
            model.RegCustomers = _customerService.GetRegCustomersForDropdown();
            model.Cities = _cityService.GetCities();
            // model.Townships = _townShipService.GetTownships();
            model.FirstParts = _firstParts;
            model.SecondParts = _secondParts;
            return View(model);
        }
    }
}

InsuranceApp/Views/RegisterForCustomers/CreateCustomers.cshtml
@model InsuranceApp.ViewModels.RegisterForCustomersViewModel

@{
    ViewBag.Title = "CreateCustomers";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Add  Customers </h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-lg-12">
                @using (Html.BeginForm("CreateCustomers", "RegisterForCustomers", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                     
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8" style="float:right;">
                                        @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                               

                                <div class="form-group">
                                    @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8" style="float:right;">
                                        @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8" style="float:right;">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8" style="float:right;">

                                        @Html.DropDownListFor(m => m.CityId, new SelectList(Model.Cities, "Id", "Name"), "Select a city", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.TownshipId, htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8" style="float:right;">
                                        @Html.DropDownListFor(m => m.TownshipId, new SelectList(Model.Townships, "Id", "TownshipName"), "Select a Township", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.TownshipId, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8" style="float:right;">
                                        @Html.Label("Male")
                                        @Html.RadioButtonFor(model => model.Gender, "Male")
                                        @Html.Label("Female")
                                        @Html.RadioButtonFor(model => model.Gender, "Female")
                                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-6">
                                <div class="form-group ">
                                    @Html.LabelFor(model => model.NRCnumber, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9 form-inline" style="float:right;">
                                        @Html.DropDownListFor(model => model.FirstPart, new SelectList(Model.FirstParts, "Value", "Value"), new { @class = "form-control col-md-2" })
                                        @Html.ValidationMessageFor(model => model.FirstPart, "", new { @class = "text-danger" })
                                        <p class="col-md-1">/</p>
                                        @Html.DropDownListFor(model => model.SecondPart, new SelectList(Model.SecondParts, "Value", "Value"), new { @class = "form-control col-md-4" })
                                        <pre class="col-md-2">(N) </pre>
                                        @Html.ValidationMessageFor(model => model.SecondPart, "", new { @class = "text-danger" })
                                        @Html.EditorFor(model => model.NRCnumber, new { htmlAttributes = new { @class = "form-control col-md-3" } })
                                        @Html.ValidationMessageFor(model => model.NRCnumber, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                               

                                <div class="form-group">
                                    @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9" style="float:right;">
                                        @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
                                    </div>
                                </div>



                                <div class="form-group">
                                    @Html.LabelFor(model => model.photo, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9" style="float:right;">
                                        <input type="file" name="file" />
                                        @Html.ValidationMessageFor(model => model.photo, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9" style="float:right;">
                                        <textarea cols="40" htmlattributes="{ class = form-control }" id="Address" name="Address" rows="4" style="border: 1px solid #d1d3e2;color: #6e707e;"></textarea>

                                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <br /><br /><br />
                                <div class="form-group">
                                  
                                    <div class="col-md-offset-4 col-md-9" style="float:right;">
                                        <input type="submit" value="Create" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>

                }
            </div>
        </div>


    </div>
</div>



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

InsuranceApp/Views/RegisterForCustomers/Edit.cshtml
@model InsuranceApp.ViewModels.RegisterForCustomersViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Edit  Customers </h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-lg-12">
                @using (Html.BeginForm("Edit", "RegisterForCustomers", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row">
                            <div class="col-md-6">
                                @Html.HiddenFor(model => model.Id)
                                <div class="form-group">
                                    @Html.LabelFor(model => model.photo, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <img src="@Url.Content(Model.photo)" height="120" width="120" />
                                        <br />
                                        <input type="file" name="file" />
                                        @Html.ValidationMessageFor(model => model.photo, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8" style="float:right;">
                                        @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8" style="float:right;">
                                        @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8" style="float:right;">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8" style="float:right;">
                                        @Html.Label("Male")
                                        @Html.RadioButtonFor(model => model.Gender, "Male")
                                        @Html.Label("Female")
                                        @Html.RadioButtonFor(model => model.Gender, "Female")
                                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9" style="float:right;">
                                        @Html.DropDownListFor(m => m.CityId, new SelectList(Model.Cities, "Id", "Name"), "Select a city..", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.TownshipId, htmlAttributes: new { @class = "control-label col-md-3" })
                                        <div class="col-md-9" style="float:right;">
                                            @Html.DropDownListFor(m => m.TownshipId, new SelectList(Model.Townships, "Id", "TownshipName"), "Select a Township", new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.TownshipId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.NRCnumber, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9 form-inline" style="float:right;">
                                        @Html.DropDownListFor(model => model.FirstPart, new SelectList(Model.FirstParts, "Value", "Value"), new { @class = "form-control col-md-2" })
                                        @Html.ValidationMessageFor(model => model.FirstPart, "", new { @class = "text-danger" })
                                        <p class="col-md-1">/</p>
                                        @Html.DropDownListFor(model => model.SecondPart, new SelectList(Model.SecondParts, "Value", "Value"), new { @class = "form-control col-md-4" })
                                        <pre class="col-md-2">(N) </pre>
                                        @Html.ValidationMessageFor(model => model.SecondPart, "", new { @class = "text-danger" })
                                        @Html.EditorFor(model => model.NRCnumber, new { htmlAttributes = new { @class = "form-control col-md-3" } })
                                        @Html.ValidationMessageFor(model => model.NRCnumber, "", new { @class = "text-danger" })
                                    </div>
                                   </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-3" })
                                        <div class="col-md-9" style="float:right;">
                                            @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-3" })
                                        <div class="col-md-9" style="float:right;">
                                            <textarea cols="40" htmlattributes="{ class = form-control }" id="Address" name="Address" rows="4" style="border: 1px solid #d1d3e2;color: #6e707e;">@ViewBag.Address</textarea>

                                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <br /><br /><br />
                                    <div class="form-group">
                                        <div class="col-md-offset-4 col-md-9" style="float:right;">
                                            <input type="submit" value="Save" class="btn btn-primary" />
                                        </div>
                                    </div>
                                </div>
                        </div>

                    </div>

                }
            </div>
        </div>
    </div>

  </div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

InsuranceApp/Views/RegisterForCustomers/Index.cshtml
@model IEnumerable<InsuranceApp.ViewModels.RegisterForCustomersViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<p>
    <button type="button" class="btn btn-outline-primary">@Html.ActionLink("Create New Customers", "CreateCustomers")</button>

</p>
<br />

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Customers List</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Photo
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CustomerName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.NRCnumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PhoneNo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                      

                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <img src="@Url.Content(item.photo)" height="100" width="100" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CustomerName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstPart)/
                                @Html.DisplayFor(modelItem => item.SecondPart) (N)
                                @Html.DisplayFor(modelItem => item.NRCnumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PhoneNo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                           
                            <td>
                                <button type="button" class="btn btn-info">@Html.ActionLink("Edit", "Edit", new { id = item.Id })</button>
                                |<button type="button" class="btn btn-info">@Html.ActionLink("Detail", "DetailUser", new { id = item.Id })</button>
                                |
                                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">Delete</button>
                                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                    <div class="modal-dialog modal-sm" role="document">
                                        <div class="modal-content">

                                            <div class="modal-body">
                                                <h4>Delete this account from application ?</h4>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                <button type="button" class="btn btn-danger">@Html.ActionLink("Delete", "Delete", new { id = item.Id })</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
        </table>
    </div>
</div>
</div>